#!/usr/bin/env bash
# Generate docs/skill-inventory.md for a bootstrapped repo.
#
# Usage:
#   ./scripts/generate-inventory.sh /path/to/repo
#
# Scans .cursor/skills/ and .cursor/agents/ for SKILL.md and agent definitions,
# reads YAML frontmatter, and produces a formatted inventory document.

set -euo pipefail

TARGET_DIR="${1:?Usage: $0 /path/to/repo}"
REPO_NAME=$(basename "$TARGET_DIR")
OUTPUT="$TARGET_DIR/docs/skill-inventory.md"

if [ ! -d "$TARGET_DIR/.cursor" ]; then
  echo "Warning: $TARGET_DIR has no .cursor/ directory. Skipping."
  exit 0
fi

mkdir -p "$TARGET_DIR/docs"

extract_frontmatter() {
  local file="$1"
  local field="$2"
  if [ -f "$file" ]; then
    awk -v field="$field" '
      /^---$/ { if (in_fm) exit; in_fm=1; next }
      in_fm && $0 ~ "^"field":" { gsub("^"field":[ ]*", ""); print; exit }
    ' "$file"
  fi
}

cat > "$OUTPUT" << 'HEADER'
# Skills & Subagents Inventory

> Auto-generated by `scripts/generate-inventory.sh`. Do not edit manually.

HEADER

echo "## Repo: $REPO_NAME" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "## Available Skills" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Skill | Access Tier | Description | Example Invocation |" >> "$OUTPUT"
echo "|---|---|---|---|" >> "$OUTPUT"

if [ -d "$TARGET_DIR/.cursor/skills" ]; then
  for skill_dir in "$TARGET_DIR/.cursor/skills"/*/; do
    [ -d "$skill_dir" ] || continue
    skill_name=$(basename "$skill_dir")
    [[ "$skill_name" == "_learnings" ]] && continue
    skill_file="$skill_dir/SKILL.md"
    if [ -f "$skill_file" ]; then
      desc=$(extract_frontmatter "$skill_file" "description")
      tier=$(extract_frontmatter "$skill_file" "access_tier")
      [ -z "$tier" ] && tier="unspecified"
      [ -z "$desc" ] && desc="(no description)"
      # Truncate long descriptions
      if [ ${#desc} -gt 80 ]; then
        desc="${desc:0:77}..."
      fi
      echo "| $skill_name | $tier | $desc | \"Use $skill_name\" |" >> "$OUTPUT"
    fi
  done
fi

echo "" >> "$OUTPUT"

echo "## Available Subagents" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Agent | Owned Files | Description |" >> "$OUTPUT"
echo "|---|---|---|" >> "$OUTPUT"

if [ -d "$TARGET_DIR/.cursor/agents" ]; then
  for agent_file in "$TARGET_DIR/.cursor/agents"/*.md; do
    [ -f "$agent_file" ] || continue
    agent_name=$(basename "$agent_file" .md)
    desc=$(extract_frontmatter "$agent_file" "description")
    [ -z "$desc" ] && desc="(no description)"
    if [ ${#desc} -gt 80 ]; then
      desc="${desc:0:77}..."
    fi
    echo "| $agent_name | .cursor/skills/$agent_name/ | $desc |" >> "$OUTPUT"
  done
fi

echo "" >> "$OUTPUT"

echo "## MCP Integrations" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| MCP Server | Tools Used | Skills That Use It |" >> "$OUTPUT"
echo "|---|---|---|" >> "$OUTPUT"

declare -A mcp_skills 2>/dev/null || true
if [ -d "$TARGET_DIR/.cursor/skills" ]; then
  for skill_file in "$TARGET_DIR/.cursor/skills"/*/SKILL.md; do
    [ -f "$skill_file" ] || continue
    skill_name=$(basename "$(dirname "$skill_file")")
    for server in user-github user-jira-utilities user-jenkins user-google-workspace user-newrelic user-splunk-mcp-server; do
      if grep -q "$server" "$skill_file" 2>/dev/null; then
        echo "| $server | (see skill) | $skill_name |" >> "$OUTPUT"
      fi
    done
  done
fi

echo "" >> "$OUTPUT"

cat >> "$OUTPUT" << 'FOOTER'
## Workspace-Level Skills (inherited)

These skills are defined at the workspace level and available to all repos:

| Skill | Description | How to Invoke |
|---|---|---|
| jira-workflow | JIRA issue operations | "Get JIRA issue IO-1234" |
| repo-lookup | Find repo location and metadata | "Where is error-management repo?" |
| service-dependency-map | Trace @celigo/* dependencies | "What depends on integrator-common-util?" |
| sync-upstream | Sync fork with upstream | "Sync this repo with upstream" |
| celigo-knowledge-advisor | Celigo platform knowledge | "How do flows work in integrator.io?" |
| celigo-connector-advisor | Connector catalog context | "Which adaptors does the Shopify connector use?" |
| skill-propagator | Cross-repo skill management | "Check for applicable skills from other repos" |
FOOTER

echo "Generated: $OUTPUT"
